import { v2 as cloudinary } from "cloudinary";
import { CloudinaryStorage } from "multer-storage-cloudinary";
import multer from "multer";
import dotenv from "dotenv";
import path from "path";

// Load env vars if they aren't loaded yet
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

// Configure Cloudinary
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

// Setup Multer Storage using Cloudinary
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: async (req, file) => {
    // Generate a unique folder or use a default one based on route
    const folder = req.baseUrl.includes("admin") ? "rentalsphere/vehicles" : "rentalsphere/users";

    // Set allowed formats
    const allowedFormats = ["jpeg", "png", "jpg", "webp"];

    return {
      folder: folder,
      allowed_formats: allowedFormats,
      // unique filename generated by cloudinary automatically
    };
  },
});

// Create Multer instance
export const upload = multer({
  storage: storage,
  limits: {
    fileSize: 5 * 1024 * 1024, // 5MB limit
  },
});
