/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as OtpVerificationRouteImport } from './routes/otp-verification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BikesRouteImport } from './routes/bikes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VehiclesSlugRouteImport } from './routes/vehicles.$slug'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin/users'
import { Route as SuperadminSecurityLogsRouteImport } from './routes/superadmin/security-logs'
import { Route as SuperadminOverviewRouteImport } from './routes/superadmin/overview'
import { Route as DashboardQueriesRouteImport } from './routes/dashboard/queries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardMfaRouteImport } from './routes/dashboard/mfa'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as BookingSlugRouteImport } from './routes/booking.$slug'
import { Route as AdminVehiclesRouteImport } from './routes/admin/vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSecurityLogsRouteImport } from './routes/admin/security-logs'
import { Route as AdminQueriesRouteImport } from './routes/admin/queries'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as PaymentKhaltiSuccessRouteImport } from './routes/payment/khalti/success'
import { Route as PaymentKhaltiFailureRouteImport } from './routes/payment/khalti/failure'
import { Route as PaymentEsewaSuccessRouteImport } from './routes/payment/esewa/success'
import { Route as PaymentEsewaFailureRouteImport } from './routes/payment/esewa/failure'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpVerificationRoute = OtpVerificationRouteImport.update({
  id: '/otp-verification',
  path: '/otp-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesRoute = BikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VehiclesSlugRoute = VehiclesSlugRouteImport.update({
  id: '/vehicles/$slug',
  path: '/vehicles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSecurityLogsRoute = SuperadminSecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminOverviewRoute = SuperadminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SuperadminRoute,
} as any)
const DashboardQueriesRoute = DashboardQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMfaRoute = DashboardMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityLogsRoute = AdminSecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueriesRoute = AdminQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const PaymentKhaltiSuccessRoute = PaymentKhaltiSuccessRouteImport.update({
  id: '/payment/khalti/success',
  path: '/payment/khalti/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentKhaltiFailureRoute = PaymentKhaltiFailureRouteImport.update({
  id: '/payment/khalti/failure',
  path: '/payment/khalti/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentEsewaSuccessRoute = PaymentEsewaSuccessRouteImport.update({
  id: '/payment/esewa/success',
  path: '/payment/esewa/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentEsewaFailureRoute = PaymentEsewaFailureRouteImport.update({
  id: '/payment/esewa/failure',
  path: '/payment/esewa/failure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bikes': typeof BikesRoute
  '/careers': typeof CareersRoute
  '/cars': typeof CarsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/queries': typeof DashboardQueriesRoute
  '/superadmin/overview': typeof SuperadminOverviewRoute
  '/superadmin/security-logs': typeof SuperadminSecurityLogsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/payment/esewa/failure': typeof PaymentEsewaFailureRoute
  '/payment/esewa/success': typeof PaymentEsewaSuccessRoute
  '/payment/khalti/failure': typeof PaymentKhaltiFailureRoute
  '/payment/khalti/success': typeof PaymentKhaltiSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bikes': typeof BikesRoute
  '/careers': typeof CareersRoute
  '/cars': typeof CarsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/queries': typeof DashboardQueriesRoute
  '/superadmin/overview': typeof SuperadminOverviewRoute
  '/superadmin/security-logs': typeof SuperadminSecurityLogsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/payment/esewa/failure': typeof PaymentEsewaFailureRoute
  '/payment/esewa/success': typeof PaymentEsewaSuccessRoute
  '/payment/khalti/failure': typeof PaymentKhaltiFailureRoute
  '/payment/khalti/success': typeof PaymentKhaltiSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bikes': typeof BikesRoute
  '/careers': typeof CareersRoute
  '/cars': typeof CarsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/queries': typeof DashboardQueriesRoute
  '/superadmin/overview': typeof SuperadminOverviewRoute
  '/superadmin/security-logs': typeof SuperadminSecurityLogsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/payment/esewa/failure': typeof PaymentEsewaFailureRoute
  '/payment/esewa/success': typeof PaymentEsewaSuccessRoute
  '/payment/khalti/failure': typeof PaymentKhaltiFailureRoute
  '/payment/khalti/success': typeof PaymentKhaltiSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bikes'
    | '/careers'
    | '/cars'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/locations'
    | '/login'
    | '/otp-verification'
    | '/press'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/superadmin'
    | '/terms'
    | '/admin/bookings'
    | '/admin/overview'
    | '/admin/queries'
    | '/admin/security-logs'
    | '/admin/users'
    | '/admin/vehicles'
    | '/booking/$slug'
    | '/dashboard/bookings'
    | '/dashboard/mfa'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/queries'
    | '/superadmin/overview'
    | '/superadmin/security-logs'
    | '/superadmin/users'
    | '/vehicles/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/superadmin/'
    | '/payment/esewa/failure'
    | '/payment/esewa/success'
    | '/payment/khalti/failure'
    | '/payment/khalti/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bikes'
    | '/careers'
    | '/cars'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/help'
    | '/locations'
    | '/login'
    | '/otp-verification'
    | '/press'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/bookings'
    | '/admin/overview'
    | '/admin/queries'
    | '/admin/security-logs'
    | '/admin/users'
    | '/admin/vehicles'
    | '/booking/$slug'
    | '/dashboard/bookings'
    | '/dashboard/mfa'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/queries'
    | '/superadmin/overview'
    | '/superadmin/security-logs'
    | '/superadmin/users'
    | '/vehicles/$slug'
    | '/admin'
    | '/dashboard'
    | '/superadmin'
    | '/payment/esewa/failure'
    | '/payment/esewa/success'
    | '/payment/khalti/failure'
    | '/payment/khalti/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bikes'
    | '/careers'
    | '/cars'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/locations'
    | '/login'
    | '/otp-verification'
    | '/press'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/superadmin'
    | '/terms'
    | '/admin/bookings'
    | '/admin/overview'
    | '/admin/queries'
    | '/admin/security-logs'
    | '/admin/users'
    | '/admin/vehicles'
    | '/booking/$slug'
    | '/dashboard/bookings'
    | '/dashboard/mfa'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/queries'
    | '/superadmin/overview'
    | '/superadmin/security-logs'
    | '/superadmin/users'
    | '/vehicles/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/superadmin/'
    | '/payment/esewa/failure'
    | '/payment/esewa/success'
    | '/payment/khalti/failure'
    | '/payment/khalti/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BikesRoute: typeof BikesRoute
  CareersRoute: typeof CareersRoute
  CarsRoute: typeof CarsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  OtpVerificationRoute: typeof OtpVerificationRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TermsRoute: typeof TermsRoute
  BookingSlugRoute: typeof BookingSlugRoute
  VehiclesSlugRoute: typeof VehiclesSlugRoute
  PaymentEsewaFailureRoute: typeof PaymentEsewaFailureRoute
  PaymentEsewaSuccessRoute: typeof PaymentEsewaSuccessRoute
  PaymentKhaltiFailureRoute: typeof PaymentKhaltiFailureRoute
  PaymentKhaltiSuccessRoute: typeof PaymentKhaltiSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-verification': {
      id: '/otp-verification'
      path: '/otp-verification'
      fullPath: '/otp-verification'
      preLoaderRoute: typeof OtpVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes': {
      id: '/bikes'
      path: '/bikes'
      fullPath: '/bikes'
      preLoaderRoute: typeof BikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehicles/$slug': {
      id: '/vehicles/$slug'
      path: '/vehicles/$slug'
      fullPath: '/vehicles/$slug'
      preLoaderRoute: typeof VehiclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/security-logs': {
      id: '/superadmin/security-logs'
      path: '/security-logs'
      fullPath: '/superadmin/security-logs'
      preLoaderRoute: typeof SuperadminSecurityLogsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/overview': {
      id: '/superadmin/overview'
      path: '/overview'
      fullPath: '/superadmin/overview'
      preLoaderRoute: typeof SuperadminOverviewRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/dashboard/queries': {
      id: '/dashboard/queries'
      path: '/queries'
      fullPath: '/dashboard/queries'
      preLoaderRoute: typeof DashboardQueriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mfa': {
      id: '/dashboard/mfa'
      path: '/mfa'
      fullPath: '/dashboard/mfa'
      preLoaderRoute: typeof DashboardMfaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-logs': {
      id: '/admin/security-logs'
      path: '/security-logs'
      fullPath: '/admin/security-logs'
      preLoaderRoute: typeof AdminSecurityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queries': {
      id: '/admin/queries'
      path: '/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AdminQueriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/payment/khalti/success': {
      id: '/payment/khalti/success'
      path: '/payment/khalti/success'
      fullPath: '/payment/khalti/success'
      preLoaderRoute: typeof PaymentKhaltiSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/khalti/failure': {
      id: '/payment/khalti/failure'
      path: '/payment/khalti/failure'
      fullPath: '/payment/khalti/failure'
      preLoaderRoute: typeof PaymentKhaltiFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/esewa/success': {
      id: '/payment/esewa/success'
      path: '/payment/esewa/success'
      fullPath: '/payment/esewa/success'
      preLoaderRoute: typeof PaymentEsewaSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/esewa/failure': {
      id: '/payment/esewa/failure'
      path: '/payment/esewa/failure'
      fullPath: '/payment/esewa/failure'
      preLoaderRoute: typeof PaymentEsewaFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminQueriesRoute: typeof AdminQueriesRoute
  AdminSecurityLogsRoute: typeof AdminSecurityLogsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminQueriesRoute: AdminQueriesRoute,
  AdminSecurityLogsRoute: AdminSecurityLogsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardMfaRoute: typeof DashboardMfaRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQueriesRoute: typeof DashboardQueriesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardMfaRoute: DashboardMfaRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQueriesRoute: DashboardQueriesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminOverviewRoute: typeof SuperadminOverviewRoute
  SuperadminSecurityLogsRoute: typeof SuperadminSecurityLogsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminOverviewRoute: SuperadminOverviewRoute,
  SuperadminSecurityLogsRoute: SuperadminSecurityLogsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BikesRoute: BikesRoute,
  CareersRoute: CareersRoute,
  CarsRoute: CarsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  OtpVerificationRoute: OtpVerificationRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TermsRoute: TermsRoute,
  BookingSlugRoute: BookingSlugRoute,
  VehiclesSlugRoute: VehiclesSlugRoute,
  PaymentEsewaFailureRoute: PaymentEsewaFailureRoute,
  PaymentEsewaSuccessRoute: PaymentEsewaSuccessRoute,
  PaymentKhaltiFailureRoute: PaymentKhaltiFailureRoute,
  PaymentKhaltiSuccessRoute: PaymentKhaltiSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
